# False config should fail
server {

    # --- Base Block ---
	
    listen :80 # and 8081, 8082, 8083 for instance

    root /www/

    index index.html index.htm index.php;

    client_max_body_size 1k # 1 kilobytes

    error_pages {
		404 /404_custom.html;
	}


    # --- Location Blocks (Routing Rules) ---
    location /{
		root /

        limit_except GET POST;
        
		autoindex false
    }

    location /tests {
		root /
        return 
			301 /new_page.html; # permanent redirect
			403; # return error on forbidden action
		}
    }

    location /uploads {
        limit_except POST LOL MANGE;

		root /uploads/

		alias /uploads/

        upload_path /uploads

    }
}

server {
	listen 127.0.0.1:8082

	root /www

	client_max_body_size 1K

	location /not-valid-route {
		root /bin
	}
}