
server {
	listen 8080

	root /core

	client_max_body_size 1K
}

server {
	listen 8081

	server_name weebserv

	root /

	index index.html home.html index.php home.php;

	access_logs /logs/logfiles/access.log

	error_logs /logs/logfiles/error.log

	client_max_body_size 50M
			    #2147483647 int_max

	error_pages {
		204 /www/error_pages/204.html;
		404 /www/error_pages/404.html;
		403 /www/error_pages/403.html;
		405 /www/error_pages/405.html;
		406 /www/error_pages/406.html;
	}

	location / {
		root /www/html
        limit_except GET POST;

		alias home
		autoindex true
    }

	location /hello {
		root /www/test
	}

	location /uploads {
        limit_except POST;

		root /uploads

		alias dropbox

        upload_path /uploads
    }

	location /www {
		root /www
		cgi_pass   127.0.0.1:9000 # localhost + port of the cgi server / NEEDED ???

		cgi_param {
			QUERY_STRING     ?querypart/of/the/url; # name location
			REQUEST_METHOD   POST;
			CONTENT_TYPE     text/html;
			CONTENT_LENGTH   42;
			SCRIPT_NAME      /cgi-bin/script;
			SCRIPT_FILENAME  /www/cgi-bin/script.py;
		}
	}

	location /tests {
		root /
		return {
			https://matias.me/nsfw/;
		}
	}
}

server {
	listen 8082

	root /core

	client_max_body_size 0
}
