
server { # this server has no location and won't do much
	listen localhost:8080

	server_name ouais-bserv

	root /core

	client_max_body_size 1K
}

server { # the main server to test
	listen 0.0.0.0:8081

	server_name weebserv

	root /

	index index.html home.html index.php home.php;

	access_logs /www/8081/logs/assess.log

	error_logs /www/8081/logs/error.log

	client_max_body_size 50M
	
	cgi_bin {
		py	/usr/bin/python3;
		php	/usr/bin/php-cgi;
	}

	error_pages {
		204 /www/8081/site/error_pages/204.html;
		404 /www/8081/site/error_pages/404.html;
	}

	location / {
		root /www/8081/site

        limit_except GET POST;

		alias home

		autoindex true
    }

	location /hello {
		root /www/8081/site/html/files

		autoindex true
	}

	location /uploads {
        limit_except POST DELETE;

		root /www/8081/site/html/

		return 302 /www/8081/site/html/form.html

		alias dropbox

		autoindex false

        upload_path /www/8081/uploads
    }

	location /tests {
		root /www/8081/site
		return {
			https://matias.me/nsfw/;
		}
	}
	
	location /bapple {
		root /www/8081/site/bapple
	}
}

server { # this server also has nothing special to do
	listen localhost:8082

	root /core

	client_max_body_size 0
}
