server {
	listen 0.0.0.0:8080

	server_name weebserv

	root /weebserv/

	index index.html index.php index.py;

	access_logs /logs/access.log

	error_logs /logs/error.log

	client_max_body_size 50M

	cgi_bin {
		py	/usr/bin/python3;
		php	/usr/bin/php-cgi;
	}

	error_pages {
		204 /error_pages/204.html;
		400 /error_pages/400.html;
		404 /error_pages/404.html;
		405 /error_pages/405.html;
		408 /error_pages/408.html;
		411 /error_pages/411.html;
		413 /error_pages/413.html;
	}

	location / {
		root /www
		limit_except GET;
		autoindex false
	}

	location /assets/ {
		root /assets
		limit_except GET;
	}

	location /uploads/ {
		root /uploads
		limit_except POST;
	}

	location /autoindex/ {
		autoindex true
	}

	location /github/ {
		return {
			https://github.com/Sukori/webserv/;
		}
	}
}
